### PR TITLE
added LoginID Text in top right

### PR DESCRIPTION
**Pull request by umutnacak**
I used API.user.email to extract the ID. I don't see a way to get the first name, at least according to this document: https://cloud.google.com/appengine/docs/python/users/userclass
I hope this is what you wanted.

### CODE REVIEW

**Comment by darianhickman** [comment]
That will work for now

**Comment by darianhickman** [comment]
Can we get those coin errors resolved too? 

create Object e
game.js:9 reduce assets Object
game.js:9 Uncaught TypeError: Cannot read property 'show' of undefined
39game.js:9 Uncaught TypeError: Cannot read property 'coins' of null
675game.js:9 Uncaught TypeError: Cannot read property 'opacity' of null

**Comment by darianhickman** [comment]
I merged and pulled your update.  I'm not seeing the login the top right
corner.  What's missing?

**Comment by umutnacak** [comment]
I'm not sure. Can you make a deploy to villagethegamedev or whatever url you are using?

**Comment by darianhickman** [comment]
it's already deployed villagegamedev2.appspot.com also I didn't see it
working on umutvillage either.

On Wed, Mar 18, 2015 at 5:53 AM, umutnacak notifications@github.com wrote:

> I'm not sure. Can you make a deploy to villagethegamedev or whatever url
> you are using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/pull/5#issuecomment-82857274
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
Yes yes I made the deploy recently. It is working on umutvillage now. Now I
am looking at villagegamedev2.

**Comment by umutnacak** [comment]
Hi,
In umutvillage's game.js there is an uglified line as var h =
API.user.email.substring(0, API.user.email.lastIndexOf("@"));
but not in villagegamedev2's game.js.
I hate to say that but are you sure that you have updated your local branch
and made the deploy afterwards?

**Pull request merged**
