### PR TITLE
added closebutton to dialogs

### PR DESCRIPTION
**Pull request by umutnacak**

### CODE REVIEW

**Comment by umutnacak** [comment]
Should we replace closeButton class (this.closeButton = new IgeUiEntity()) with IgeEntity() or IgeUiElement()?
I wanted to use IgeEntity but accidentally commited as IgeUiEntity. So you may want to replace it with the proper class.

**Comment by darianhickman** [comment]
Is there simple command to approve a pull request and merge to master? I
haven't used that feature yet.

On Wed, Mar 11, 2015 at 1:25 PM, umutnacak notifications@github.com wrote:

> Should we replace closeButton class (this.closeButton = new IgeUiEntity())
> with IgeEntity() or IgeUiElement()?
> I wanted to use IgeEntity but accidentally commited as IgeUiEntity. So you
> may want to replace it with the proper class.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/pull/1#issuecomment-78311882
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
I don't know either. I am getting an error when I try a git push: umutnacak$ git push -u origin closebutton
remote: Permission to darian311/VillageMakeover.git denied to umutnacak.
fatal: unable to access 'https://github.com/darian311/VillageMakeover.git/': The requested URL returned error: 403
If you know the solution to this error I can make a git push, so closebutton branch is here.

**Comment by umutnacak** [comment]
There is an info message in front of me: This pull request can be automatically merged by project collaborators.
So there should be an 'automatic' command for merging.

**Comment by darianhickman** [comment]
I think it's merged now.

**Pull request merged**
